### ISSUE TITLE
When creating a navigation with the name of a past deleted navigation the slug/url increments

### ISSUE THREAD

**Issue by fabiennecornel** [VirtusLab/strapi-plugin-navigation#378] opened 2023-09-15 15:20 UTC
Hello I'm on Strapi version 4.13.6 and this plugin version 2.2.14.

In this screen (don't pay attention to the id in this picture):
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/3ef72641-d052-4d4d-8f62-2962b4edd3a0)
When I create a navigation the **first time**, the content I put in inside that is accessible by the URL /api/navigation/render/waarschuwingen
Strapi response:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/86ea24f6-0ea1-4ba4-bfff-9fbe84ad5c72)
Then I delete that navigation by pressing the trash bin and pressing delete:
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/0da4ba56-dc29-4018-8c3d-4936e2b6f951)
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/fde9f72e-d98c-42fb-995c-d45c62d1ee30)

It no longer shows in the navigations, which is good.

So then I create a new navigation with the name I used before, but this time the content is accessible by /api/navigation/render/waarschuwingen-1
Strapi response: 
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/6683170d-7ccf-4b1d-b8f9-57db08ed1e52)

Is it possible to make the slug/URL available again once the navigation it belonged to has been deleted?

**Comment by CodeVoyager** [comment] 2023-09-20 13:17
Hi @fabiennecornel 

Slug generator takes current items present in navigations table with slug starting with result of title first pass mapping. Can you confirm that in `navigations` table there are not navigations with `uiRouterKey` similar to what you want to generate?

You could have some leftovers due to db lock issues described in these two issues https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/347 https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/issues/345 (PR to address these issues is in review)

**Comment by fabiennecornel** [comment] 2023-09-27 11:07
Hello,

The navigation gets removed from the `navigations` table but the navigations_items aren't deleted and check the `ui_router_key` column here.
![image](https://github.com/VirtusLab-Open-Source/strapi-plugin-navigation/assets/100563015/80789589-93dd-4f1e-8c7c-a5fbf16cf3ef)

**Comment by CodeVoyager** [comment] 2023-09-27 13:23
Hi @fabiennecornel ,

We will investigate this issue and will be back (hopefully) soon

**Comment by cyp3rius** [comment] 2023-09-29 05:28
Version `v2.2.15` contains #347 #345. Check please @fabiennecornel if your issue was solved by this

**Comment by fabiennecornel** [comment] 2023-09-29 10:18
Updated to 2.2.15 and the issue is still present.

**Comment by cyp3rius** [comment] 2023-09-29 10:19
ok so seems it's not connected. @CodeVoyager  up to you

**Comment by CodeVoyager** [comment] 2023-09-29 12:54
After deeper look root cause was lack of cascade item cleanup on navigation deletion. Connected PR covers the issue.

**Comment by cyp3rius** [comment] 2023-10-03 14:46
Released as `v2.2.16`

**Closed as completed by cyp3rius** 2023-10-03 14:46 UTC
Labels: help wanted, solved, v4
